### ISSUE TITLE
Command line arguments are not working in CommandLineRunner

### ISSUE THREAD

**Issue by kevinabrandon** [zxing/zxing#518]
When I run the CommandLineRunner in javase it works unless I try to pass it command line arguments (like --try_harder and --crop).

Here is the error message:
>Exception in thread "main" java.lang.NoClassDefFoundError: com/beust/jcommander/JCommander
>	at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:52)
>Caused by: java.lang.ClassNotFoundException: com.beust.jcommander.JCommander
>	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
>	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
>	at java.security.AccessController.doPrivileged(Native Method)
>	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
>	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
>	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
>	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
>	... 1 more

I tried it both with the jar files I built, and with the ones hosted at the Maven Release Repository.  It works on 3.2.0, but is broken on 3.2.1.

**Comment by srowen** [comment]
How are you running this? the command-line programs need jcommander, so it has to be included in some way on the classpath. It's correctly specified in the Maven build.

**Comment by kevinabrandon** [comment]
I'm trying to follow the instructions on the [get started developing wiki page](https://github.com/zxing/zxing/wiki/Getting-Started-Developing#javase).  Basically I'm running the  command: 

    java -cp javase/target/javase-x.y.z.jar:core/target/core-x.y.z.jar com.google.zxing.client.j2se.CommandLineRunner [URL | FILE]

Here are the steps I originally took (which failed):

    git clone htp://github.com/zxing/zxing
    mvn package
    java -cp javase/target/javase-3.2.2-SNAPSHOT.jar:core/target/core-3.2.2-SNAPSHOT.jar com.google.zxing.client.j2se.CommandLineRunner BigTestFile.png --crop=811,543,223,263 --try_harder

I then tried this and it worked:

    wget http://central.maven.org/maven2/com/google/zxing/core/3.2.0/core-3.2.0.jar
    wget http://central.maven.org/maven2/com/google/zxing/javase/3.2.0/javase-3.2.0.jar
    java -cp javase-3.2.0.jar:core-3.2.0.jar com.google.zxing.client.j2se.CommandLineRunner BigTestFile.png --crop=811,543,223,263 --try_harder

However, when I do the same for 3.2.1 it fails.

**Comment by srowen** [comment]
Ah, right. We need a slightly different set of instructions now that jcommander is a dependency. Really you need to include a jar that bundles the dependencies. Let me add that. In the meantime if you add the jcommander jar to your classpath this should work too. But a bundled jar would mean you only need one jar here, and not even the core one, which would be nice.

**Comment by srowen** [comment]
Have a look at the change above and the new instructions at https://github.com/zxing/zxing/wiki/Getting-Started-Developing

**Comment by kevinabrandon** [comment]
Excellent!  Thanks for the help!

**Comment by miverson** [comment]
To clarify these instructions slightly, I needed to execute

    mvn install

in the root before performing the 

    mvn -DskipTests package assembly:single

command in java2se/

**Comment by srowen** [comment]
Yeah I'll update to say `install` to build for completeness.

**Comment by Mairu** [comment]
Would be nice, if this assembled jar file would be downloadable in https://repo1.maven.org/maven2/com/google/zxing/javase/
